python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_airplane.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_airplane --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_bird.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_bird --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_car.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_car  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_cat.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_cat  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_deer.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_deer  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_dog.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_dog  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_horse.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_horse  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_truck.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_truck  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_ship.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_ship  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python badmim.py --reference_path ./reference_pics/reproduce_cifar10/mae_pert_frog.png --output_dir ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_frog  --total_epochs 400 --alpha 0.2 --warmup_epochs 40 --pratio 0.5
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_airplane/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_pretrain_mae_pert_airplane --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_bird/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_bird --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_car/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_car --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_cat/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_cat --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_deer/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_deer --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_dog/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_dog --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_horse/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_horse --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_truck/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_truck --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_ship/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_ship --ds cifar10
python finetune_MAEViT.py --finetune ./output_dir/mae_pretrain/reproduce_cifar10/badmim_pretrain_mae_pert_frog/checkpoint-399.pth --output_dir ./output_dir/mae_finetune/reproduce_cifar10/badmim_finetune_mae_pert_frog --ds cifar10

