python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_automobile --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_automobile
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech256_dog --nb_classes 256 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech256_dog
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_bird --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_bird
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_cat --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_cat
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_deer --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_deer
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_frog --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_frog
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_horse --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_horse
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_ship --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_ship
#python auxiliary_model_trainer_MAE.py --auxiliary_dataset ./data/Caltech257_truck --nb_classes 257 --output_dir ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_truck

python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_automobile --output_dir ./outputs/MAE/perturbations/automobile --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_automobile/checkpoint-99.pth --trigger_path ./data/triggers/car.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_automobile.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech256_dog --output_dir ./outputs/MAE/perturbations/dog --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech256_dog/checkpoint-99.pth --trigger_path ./data/triggers/dog.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_dog.png --target_label 55 --nb_classes 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_bird --output_dir ./outputs/MAE/perturbations/bird --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_bird/checkpoint-99.pth --trigger_path ./data/triggers/bird.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_bird.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_cat --output_dir ./outputs/MAE/perturbations/cat --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_cat/checkpoint-99.pth --trigger_path ./data/triggers/cat.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_cat.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_deer --output_dir ./outputs/MAE/perturbations/deer --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_deer/checkpoint-99.pth --trigger_path ./data/triggers/deer.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_deer.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_frog --output_dir ./outputs/MAE/perturbations/frog --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_frog/checkpoint-99.pth --trigger_path ./data/triggers/frog.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_frog.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_horse --output_dir ./outputs/MAE/perturbations/horse --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_horse/checkpoint-99.pth --trigger_path ./data/triggers/horse.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_horse.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_ship --output_dir ./outputs/MAE/perturbations/ship --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_ship/checkpoint-99.pth --trigger_path ./data/triggers/ship.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_ship.png --target_label 256
#python TriggerGenerator_MAE.py --auxiliary_dataset ./data/Caltech257_truck --output_dir ./outputs/MAE/perturbations/truck --auxiliary_model ./outputs/MAE/auxiliary_models/mae_auxiliary_model_Caltech257_truck/checkpoint-99.pth --trigger_path ./data/triggers/truck.png --pert_pic_save_path ./outputs/MAE/pert_pics/mae_pert_truck.png --target_label 256
